version: '3.4'

services:
    pentaho-server:
        image: ibluewind/pentaho-server:h2db
        container_name: pentaho-server
        hostname: pentaho-server
        volumes:
            - hsqldb-data:/opt/pentaho/server/pentaho-server/data/hsqldb
            - jackrabbit-data:/opt/pentaho/server/pentaho-server/pentaho-solutions/system/jackrabbit/repository
        ports: 
            - 8080:8080
            - 9051:9051
        networks: 
            - xr-analysis
    carte-master:
        image: ibluewind/pentaho-carte:0.1
        container_name: carte-master
        hostname: carte-master
        environment:
            - PENTAHO_SERVER=pentaho-server
            - CARTE_MASTER=Y
            - CARTE_MASTER_HOSTNAME=carte-master
            - CARTE_MASTER_PORT=11000
        ports: 
            - 11000:11000
        networks:
            - xr-analysis
        depends_on: 
            - pentaho-server
    xr-mysql:
        image: mysql:5.7
        container_name: xr-mysql
        hostname: xr-mysql
        volumes:
            - ${XR_MYSQL_VOLUME}:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1Qaz@Wsx
        ports:
            - 4306:3306
        networks:
            - xr-analysis
    xr-storage:
        image: store/minio/minio:RELEASE.2020-12-29T23-29-29Z
        container_name: xr-storage
        hostname: xr-storage
        environment:
            - MINIO_ACCESS_KEY=xr_user
            - MINIO_SECRET_KEY=xr_user_secret_key
        ports:
            - 9000:9000
        command: ["server", "/data"]
        volumes:
            - ${XR_STORAGE_VOLUME}:/data
        networks:
            - xr-analysis
networks: 
    xr-analysis:
volumes: 
    hsqldb-data:
    jackrabbit-data: