version: '3.4'

services:
    pentaho-server:
        image: ibluewind/pentaho-server:mysql
        container_name: pentaho-server
        hostname: pentaho-server
        environment: 
            - MYSQL_HOST=pentaho-mysql
            - MYSQL_USER=root
            - MYSQL_PASSWD=1Qaz@Wsx
            - MYSQL_PORT=3306
        ports: 
            - 8080:8080
            - 9051:9051
        networks: 
            - xr-analysis
        depends_on: 
            - pentaho-mysql
    # carte-master:
    #     image: ibluewind/pentaho-carte:1.0
    #     container_name: carte-master
    #     hostname: carte-master
    #     environment:
    #         - PENTAHO_SERVER=pentaho-server
    #         - CARTE_MASTER=Y
    #         - CARTE_MASTER_HOSTNAME=carte-master
    #         - CARTE_MASTER_PORT=11000
    #     ports: 
    #         - 11000:11000
    #     networks:
    #         - xr-analysis
    #     depends_on: 
    #         - pentaho-server
    pentaho-mysql:
        image: mysql:5.7.34
        container_name: pentaho-mysql
        hostname: pentaho-mysql
        volumes:
            - ${PENTAHO_MYSQL_VOLUME}:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1Qaz@Wsx
        ports:
            - 4306:3306
        networks:
            - xr-analysis
    xr-mysql:
        image: mysql:5.7.34
        container_name: xr-mysql
        hostname: xr-mysql
        volumes:
            - ${XR_MYSQL_VOLUME}:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1Qaz@Wsx
        ports:
            - 3306:3306
        networks:
            - xr-analysis
        depends_on: 
            - pentaho-mysql
    xr-storage:
        image: store/minio/minio:RELEASE.2020-12-29T23-29-29Z
        container_name: xr-storage
        hostname: xr-storage
        environment:
            - MINIO_ACCESS_KEY=xr_user
            - MINIO_SECRET_KEY=xr_user_secret_key
        ports:
            - 9000:9000
        command: ["server", "/data"]
        volumes:
            - ${XR_STORAGE_VOLUME}:/data
        networks:
            - xr-analysis
    mssql_svr:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: mssql_svr
        hostname: mssql_svr
        volumes:
            - ${XR_MSSQL_VOLUME}:/var/opt/mssql/data
        environment: 
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=1Qaz@Wsx
        ports: 
            - 1433:1433
        networks: 
            - xr-analysis
networks: 
    xr-analysis:
