version: '3.4'

services:
    pentaho-server:
        image: ibluewind/pentaho-server:mysql
        container_name: pentaho-server
        hostname: pentaho-server
        environment: 
            - MYSQL_HOST=pentaho-mysql
            - MYSQL_USER=root
            - MYSQL_PASSWD=1Qaz@Wsx
            - MYSQL_PORT=3306
        ports: 
            - 8080:8080
            - 9051:9051
        networks: 
            - xr-analysis
        depends_on: 
            - pentaho-mysql
    pentaho-mysql:
        image: mysql:5.7.34
        command: --default-authentication-plugin=mysql_native_password
        container_name: pentaho-mysql
        hostname: pentaho-mysql
        volumes:
            - ./mysql/data8:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1Qaz@Wsx
        ports:
            - 4306:3306
        networks:
            - xr-analysis
networks: 
    xr-analysis:
