version: '3.4'

services:
  sql1:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql1
    hostname: sql1
    volumes:
      - /data/mssql-data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1Qaz@Wsx
    ports:
      - 1433:1433
